---
- name: "Deployment"
  hosts: localhost
  vars_files:
  - access-key.vars
  vars:
    key_name: "devops-key"
  tasks:
    - name: collecting instance info
      ec2_instance_info:
        region: "{{region}}"
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        filters:
          "tag:Name": Asg
          instance-state-name: ["running"]
      register: asg_info


    - name: Creating inventory
      add_host: 
        host: "{{ item.public_ip_address }}"
        groupname: newasg
        ansible_host: "{{ item.public_ip_address }}"
        ansible_port: 22
        ansible_user: "ec2-user"
        ansible_ssh_private_key_file: "{{key_name}}.pem"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items:
      - "{{ asg_info.instances }}"
- name: "updating ASG"
  hosts: newasg
  become: true
  serial: 1
  vars:
    git_url: "https://github.com/gigingeorge/aws-elb-site.git"
    owner: "apache"
    group: "apache"
  tasks:
    - name: install modules
      yum:
        name: "{{item}}"

      with_items:
      - httpd
      - git
      - php 
    - name: enable-restart
      service:
        name: httpd
        state: restarted
        enabled: true
    - name: "downloading from git"
      git:
        repo: "{{git_url}}"
        dest: /var/myweb/
      register: git_status
    - name: "disabling health check"
      when: git_status.changed == true
      service:
        name: httpd
        state: stopped
    - name: Pause to offload from elb
      when: git_status.changed == true
      pause:
        seconds: 25
    - name: copying contents
      when: git_status.changed == true
      copy:
        src: /var/myweb/
        dest: /var/www/html/
        owner: "{{owner}}"
        group: "{{group}}"
        remote_src: true
    - name: "Enabling health check"
      when: git_status.changed == true

      service:
        name: httpd
        state: started

    - name: Pause to  load to elb
      when: git_status.changed == true
      pause:
        seconds: 25
